### ISSUE TITLE
Gender view is smaller than any other view in profile fragment

### ISSUE THREAD

**Issue by evyatarv** [ozerynir/DiveApp#17]
There is sizes diff between gender view to any other view. 
(seen in Samsung Galaxy S5)

**Comment by N-o-Z** [comment]
I'll fix the bug for the next merge. Can you send a screen capture?

**Comment by N-o-Z** [comment]
Can you check with Shani's phone to see it was resolved?

**Comment by evyatarv** [comment]
this issue has not resolved. 

checked on my Nexus.
